from typing import Annotated, List, Literal, Optional, Union
from pydantic import BaseModel, ConfigDict, Field

from llm_gateway.misc.enums import OpenAiMessageAudioFormat, OpenAiMessageContentType, OpenAiMessageImageDetail, \
    OpenAiMessageRole, OpenAiMessageToolCallType, OpenAiResponseAudioFormat
from ..chat_completion import ChatCompletionRequest as InternalChatCompletionRequest


class ChatCompletionMessageFile(BaseModel):
    file_data: Optional[str] = Field(
        None,
        description='The base64 encoded file data, used when passing the file to the model as a string.',
    )
    file_id: Optional[str] = Field(
        None,
        description='The ID of an uploaded file to use as input.',
    )
    filename: Optional[str] = Field(
        None,
        description='The name of the file, used when passing the file to the model as a string.',
    )


class ChatCompletionMessageInputAudio(BaseModel):
    data: str = Field(
        ...,
        description='Base64 encoded audio data.',
    )
    format: Optional[OpenAiMessageAudioFormat] = Field(
        None,
        description='The format of the encoded audio data.',
    )


class ChatCompletionMessageImageUrl(BaseModel):
    url: str = Field(
        ...,
        description='Either a URL of the image or the base64 encoded image data.',
    )
    detail: Optional[OpenAiMessageImageDetail] = Field(
        None,
        description='Specifies the detail level of the image.',
    )


class ChatCompletionMessageContentPartAudio(BaseModel):
    type: Literal[OpenAiMessageContentType.INPUT_AUDIO] = Field(
        OpenAiMessageContentType.INPUT_AUDIO,
        description='The type of content part.',
    )
    input_audio: ChatCompletionMessageInputAudio = Field(
        ...,
        description='The audio content.',
    )


class ChatCompletionMessageContentPartFile(BaseModel):
    type: Literal[OpenAiMessageContentType.FILE] = Field(
        OpenAiMessageContentType.FILE,
        description='The type of content part.',
    )
    file: ChatCompletionMessageFile = Field(
        ...,
        description='The file content.',
    )


class ChatCompletionMessageContentPartImage(BaseModel):
    type: Literal[OpenAiMessageContentType.IMAGE_URL] = Field(
        OpenAiMessageContentType.IMAGE_URL,
        description='The type of content part.',
    )
    image_url: ChatCompletionMessageImageUrl = Field(
        ...,
        description='The image URL content.',
    )


class ChatCompletionMessageContentPartRefusal(BaseModel):
    type: Literal[OpenAiMessageContentType.REFUSAL] = Field(
        OpenAiMessageContentType.REFUSAL,
        description='The type of content part.',
    )
    refusal: str = Field(
        ...,
        description='The refusal message generated by the model.',
    )


class ChatCompletionMessageContentPartText(BaseModel):
    type: Literal[OpenAiMessageContentType.TEXT] = Field(
        OpenAiMessageContentType.TEXT,
        description='The type of content part.',
    )
    text: str = Field(
        ...,
        description='The text content.',
    )


ChatCompletionMessageContentPartAssistant = Annotated[
    Union[
        ChatCompletionMessageContentPartRefusal,
        ChatCompletionMessageContentPartText,
    ],
    Field(discriminator='type'),
]


ChatCompletionMessageContentPartUser = Annotated[
    Union[
        ChatCompletionMessageContentPartAudio,
        ChatCompletionMessageContentPartFile,
        ChatCompletionMessageContentPartImage,
        ChatCompletionMessageContentPartText,
    ],
    Field(discriminator='type'),
]


class ChatCompletionMessageAssistantAudio(BaseModel):
    id: str = Field(
        ...,
        description='Unique identifier for a previous audio response from the model.',
    )


class ChatCompletionMessageCustomCall(BaseModel):
    input: str = Field(
        ...,
        description='The input for the custom tool call generated by the model.',
    )
    name: str = Field(
        ...,
        description='The name of the custom tool to call.',
    )


class ChatCompletionMessageFunctionCall(BaseModel):
    arguments: str = Field(
        ...,
        description='The arguments to call the function with, as generated by the model in JSON format.',
    )
    name: str = Field(
        ...,
        description='The name of the function to call.',
    )


class ChatCompletionMessageToolCallCustom(BaseModel):
    type: Literal[OpenAiMessageToolCallType.CUSTOM] = Field(
        OpenAiMessageToolCallType.CUSTOM,
        description='The type of the tool.',
    )
    id: str = Field(
        ...,
        description='The ID of the tool call.',
    )
    custom: ChatCompletionMessageCustomCall = Field(
        ...,
        description='The custom tool that the model called.',
    )


class ChatCompletionMessageToolCallFunction(BaseModel):
    type: Literal[OpenAiMessageToolCallType.FUNCTION] = Field(
        OpenAiMessageToolCallType.FUNCTION,
        description='The type of the tool.',
    )
    id: str = Field(
        ...,
        description='The ID of the tool call.',
    )
    function: ChatCompletionMessageFunctionCall = Field(
        ...,
        description='The function that the model called.',
    )


ChatCompletionMessageToolCall = Annotated[
    Union[
        ChatCompletionMessageToolCallCustom,
        ChatCompletionMessageToolCallFunction,
    ],
    Field(discriminator='type'),
]


class ChatCompletionMessageAssistant(BaseModel):
    role: Literal[OpenAiMessageRole.ASSISTANT] = Field(
        OpenAiMessageRole.ASSISTANT,
        description='The role of the messages author, in this case assistant.',
    )
    audio: Optional[ChatCompletionMessageAssistantAudio] = Field(
        None,
        description='Data about a previous audio response from the model.',
    )
    content: Optional[Union[str, List[ChatCompletionMessageContentPartAssistant]]] = Field(
        None,
        description='The contents of the assistant message. Required unless tool_calls or function_call '
                    'is specified.',
    )
    function_call: Optional[ChatCompletionMessageFunctionCall] = Field(
        None,
        description='Deprecated and replaced by tool_calls. The name and arguments of a function that '
                    'should be called, as generated by the model.',
        deprecated=True,
    )
    name: Optional[str] = Field(
        None,
        description='An optional name for the participant.',
    )
    refusal: Optional[str] = Field(
        None,
        description='The refusal message generated by the model.',
    )
    tool_calls: Optional[List[ChatCompletionMessageToolCall]] = Field(
        None,
        description='The tool calls generated by the model, such as function calls.',
    )


class ChatCompletionMessageDeveloper(BaseModel):
    role: Literal[OpenAiMessageRole.DEVELOPER] = Field(
        OpenAiMessageRole.DEVELOPER,
        description='The role of the messages author, in this case developer.',
    )
    content: str | List[ChatCompletionMessageContentPartText] = Field(
        ...,
        description='The contents of the developer message.',
    )
    name: Optional[str] = Field(
        None,
        description='An optional name for the participant.',
    )


class ChatCompletionMessageFunction(BaseModel):
    role: Literal[OpenAiMessageRole.FUNCTION] = Field(
        OpenAiMessageRole.FUNCTION,
        description='The role of the messages author, in this case function.',
    )
    content: str = Field(
        ...,
        description='The contents of the function message.',
    )
    name: str = Field(
        ...,
        description='The name of the function to call.',
    )


class ChatCompletionMessageSystem(BaseModel):
    role: Literal[OpenAiMessageRole.SYSTEM] = Field(
        OpenAiMessageRole.SYSTEM,
        description='The role of the messages author, in this case system.',
    )
    content: str | List[ChatCompletionMessageContentPartText] = Field(
        ...,
        description='The contents of the system message.',
    )
    name: Optional[str] = Field(
        None,
        description='An optional name for the participant.',
    )


class ChatCompletionMessageTool(BaseModel):
    role: Literal[OpenAiMessageRole.TOOL] = Field(
        OpenAiMessageRole.TOOL,
        description='The role of the messages author, in this case tool.',
    )
    content: str | List[ChatCompletionMessageContentPartText] = Field(
        ...,
        description='The contents of the tool message.',
    )
    tool_call_id: str = Field(
        ...,
        description='Tool call that this message is responding to.',
    )


class ChatCompletionMessageUser(BaseModel):
    role: Literal[OpenAiMessageRole.USER] = Field(
        OpenAiMessageRole.USER,
        description='The role of the messages author, in this case user.',
    )
    content: str | List[ChatCompletionMessageContentPartUser] = Field(
        ...,
        description='The contents of the user message.',
    )
    name: Optional[str] = Field(
        None,
        description='An optional name for the participant.',
    )


ChatCompletionMessage = Annotated[
    Union[
        ChatCompletionMessageAssistant,
        ChatCompletionMessageDeveloper,
        ChatCompletionMessageFunction,
        ChatCompletionMessageSystem,
        ChatCompletionMessageTool,
        ChatCompletionMessageUser,
    ],
    Field(discriminator='role'),
]


class ChatCompletionRequestAudio(BaseModel):
    format: OpenAiResponseAudioFormat = Field(
        ...,
        description='Specifies the output audio format.',
    )
    voice: str = Field(
        ...,
        description='The voice the model uses to respond.',
    )


class ChatCompletionRequest(BaseModel):
    """
    A request to the OpenAI chat completion endpoint.
    """
    model_config = ConfigDict(extra='allow')

    model: str = Field(
        ...,
        description='The model to use.',
    )
    messages: List[ChatCompletionMessage] = Field(
        default_factory=list,
        description='A list of messages comprising the conversation so far.',
    )
    audio: Optional[ChatCompletionRequestAudio] = Field(
        None,
        description='Parameters for audio output. Required when audio output is requested with '
                    'modalities: ["audio"].',
    )
    frequency_penalty: Optional[float] = Field(
        None,
        description='Number between -2.0 and 2.0. Positive values penalize new tokens based on their '
                    'existing frequency in the text so far, decreasing the model\'s likelihood to repeat '
                    'the same line verbatim.',
        ge=-2.0,
        le=2.0,
    )

    def to_internal(self) -> InternalChatCompletionRequest:
        """
        Convert the request to the internal representation used by the rest of the codebase.
        """
        return InternalChatCompletionRequest(
            model=self.model,
            payload=self.model_dump(mode='json', exclude_none=True),
        )
