from datetime import datetime, timezone
from pydantic import BaseModel, Field

from llm_gateway.misc.enums import WorkerType
from .model import Model


class Worker(BaseModel):
    id: int = Field(
        None,
        description='The id of the worker, generated by the database.',
    )
    type: WorkerType = Field(
        ...,
        description='The type of the worker.',
    )
    secret_hash: str = Field(
        ...,
        description='The secret hash of the worker, used to authenticate the worker. Argon 2 algorithm.',
    )


class WorkerCapability(BaseModel):
    models: list[Model] = Field(
        ...,
        description='The models that the worker is currently serving.',
    )
    max_concurrency: int = Field(
        ...,
        description='The maximum number of concurrent requests that the worker can handle.',
    )


class WorkerState(BaseModel):
    worker: Worker = Field(
        ...,
        description='The worker that this state describes.',
    )
    models: list[Model] = Field(
        ...,
        description='The models that the worker is currently serving.',
    )
    max_concurrency: int = Field(
        ...,
        description='The maximum number of concurrent requests that the worker can handle.',
    )
    active_requests: set[str] = Field(
        default_factory=set,
        description='The ids of the active requests that the worker is currently handling.',
    )
    healthy: bool = Field(
        True,
        description='Whether the worker is healthy.',
    )

    last_report: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description='The last time the worker reported something, either heartbeat or a response, etc.',
    )
